### ISSUE TITLE
Auto roll damage if there is no attack for an item

### ISSUE THREAD

**Issue by slcao2** [slcao2/FoundryVTT-QuickRolls#10]
If there is no attack roll to automatically roll, auto roll the damage instead if it exists.

**Comment by cs96and** [comment]
This looks like it works when an item, spell or feat is rolled from the sheet, but if you drag it to the macro bar and click it from there, then it doesn't auto roll the damage.

**Comment by slcao2** [comment]
@cs96and Guess I have a new thing to add to my testing. It should be fixed now. Give it a shot.
