### ISSUE TITLE
Available for PF2e?

### ISSUE THREAD

**Issue by Puddinglord** [slcao2/FoundryVTT-QuickRolls#13]
I love the idea and was wondering if this supports PF2e or is there was planned support.

**Comment by slcao2** [comment]
Currently, it is not likely to work with PF2e as it uses specific logic related to the dnd5e system but you're welcome to give it a try and see if it does but I wouldn't count on it. No plans as of now to support PF2e as it would likely require a bit of overhaul to get it working and I'm not really knowledgable on the PF2e ruleset as I only play dnd5e. If there's significant interest in it, I may consider it but as of now, nothing planned. Sorry :(

**Comment by Puddinglord** [comment]
No worries at all! I shall poke around to see if it works and I appreciate you getting back to me.

For now I'll close this issue. If I come across anything, I'll open another.
