### ISSUE TITLE
"Place Measured Template" is broken on spells

### ISSUE THREAD

**Issue by Loqu7us** [slcao2/FoundryVTT-QuickRolls#18]
Casted spells do not populate in chat if "Place Measured Template" box is checked. If the box is unchecked, the spell casts in chat and damage rolls correctly. However, the "Place Measured Template" button in the chat box does not function. Tested on 0.7.5 and 0.7.7, and in dnd5e system versions 0.98 and 1.1.1. Also tested with all other modules off and isolated the issue to Quick rolls.

**Comment by cs96and** [comment]
Yes, having the same issue here too

**Comment by slcao2** [comment]
Oops forgot to retest the spells. Looks like something wonky is happening that wasn't happening before. I'll look into a fix.

**Comment by slcao2** [comment]
@cs96and @Loqu7us Fix should be out. Hopefully it's working properly for you folks.

**Comment by cs96and** [comment]
yep works great now, thanks
