### ISSUE TITLE
Hover help for (Dis)Advantage Button

### ISSUE THREAD

**Issue by apoapostolov** [slcao2/FoundryVTT-QuickRolls#2]
It is easy to forget what button needs to be pressed when Disadvantage. A hover message mentioning CTRL would help.

**Comment by slcao2** [comment]
Thanks for the input. It currently uses the buttons in the same way that the core FoundryVTT uses the buttons as well so I was hoping it wouldn't be too difficult to remember. A tooltip is a good idea though. If I get some time, I'll maybe look into adding it.

**Comment by apoapostolov** [comment]
Thanks. This is mostly needed for my players who don't learn many keybindings.
