### ISSUE TITLE
Proficiency bonus being applied to thrown items

### ISSUE THREAD

**Issue by cs96and** [slcao2/FoundryVTT-QuickRolls#21]
Thrown items (e.g. alchemists fire) are improvised weapons.  However it seems that the proficiency bonus is being applied to the attack roll.  Better Rolls seems to handle this correctly, but Quick Rolls does not.

![image](https://user-images.githubusercontent.com/898086/100812824-d8ca9c00-3435-11eb-9049-d56cc9963fd1.png)

**Comment by cs96and** [comment]
I think this may be an issue in the dnd5e system.  I've reported it there too
https://gitlab.com/foundrynet/dnd5e/-/issues/839

**Comment by slcao2** [comment]
Hmm if it's happening in vanilla then it is likely a dnd5e system issue. I can circle back around to this at some point if it doesn't get resolved on the dnd5e issue.

**Comment by slcao2** [comment]
@cs96and Issue should be fixed now. Give it whirl.

**Comment by cs96and** [comment]
Excellent, thanks!
