### ISSUE TITLE
Attacks and spells go to public chat when default mode is set to Self Roll

### ISSUE THREAD

**Issue by cs96and** [slcao2/FoundryVTT-QuickRolls#23]
If you make an attack or spell roll when the default mode is set to "Self Roll", the attack goes to the public chat....

![image](https://user-images.githubusercontent.com/898086/101071619-c31fb880-3594-11eb-8eda-41437e45e098.png)

This differs from a Private GM roll, which does the correct thing...

![image](https://user-images.githubusercontent.com/898086/101071895-1eea4180-3595-11eb-9487-effd86fdb73e.png)

However it seems that vanilla foundry also has the same problem, yet Better Rolls does the correct thing
https://gitlab.com/foundrynet/dnd5e/-/issues/842

**Comment by slcao2** [comment]
Oh man if you were an NPC pokemon trainer you'd definitely be the bug catcher. Thanks for the find! The module uses code out of the dnd5e system so some of the issues end up being linked to similar things with the system. I'll update once the main system has been updated.

**Comment by cs96and** [comment]
> Oh man if you were an NPC pokemon trainer you'd definitely be the bug catcher. Thanks for the find! 

Hehe, I've just started using Foundry and don't like the vanilla rolling system and, like you, there are things about Better Rolls that I don't like (e.g. auto roll damage).  It also seems to have workarounds for various underlying bugs, so most people don't notice them.  I'd love to properly switch over to Quick Rolls once all the issues are sorted out.

**Comment by slcao2** [comment]
@cs96and Issue should be fixed now. Give it whirl.

**Comment by cs96and** [comment]
Excellent, thanks!
