### ISSUE TITLE
Feature request: option to turn off the re-roll button, or somehow make it more compact

### ISSUE THREAD

**Issue by cs96and** [slcao2/FoundryVTT-QuickRolls#29]
Although the re-roll feature is nice, it does expand the card vertically quite a bit, especially if there is attack and damage.  Could you either...

1. Add an option to disable them
2. Make them more compact, e.g by somehow squeezing the button next to the dice result

**Comment by slcao2** [comment]
@cs96and Hmm currently the minimum sizing for the header is 15px as that's how much the text takes up. I could reduce the button size down to match the header text size which would compact it a little bit more.

**Comment by slcao2** [comment]
@cs96and The reroll button should be slightly more compact vertically now. If that still doesn't work for you, I can look into adding a toggle for the reroll button, which I might do anyway.
