### ISSUE TITLE
Add chat buttons to add or remove hp from tokens

### ISSUE THREAD

**Issue by mech-tools** [slcao2/FoundryVTT-QuickRolls#33]
Hello,

This module is better and better! Congrats.
How about adding buttons to remove hp from selected tokens in the dms section?

**Comment by slcao2** [comment]
@DarKDinDoN Thanks! Good suggestion. I'll look to implement something similar to what exists for the damage rolls now, potentially broken down by each damage roll type. Coming soontm.

**Comment by slcao2** [comment]
@DarKDinDoN Feature should be added. Give it a try!

**Comment by mech-tools** [comment]
@slcao2 Perfect!!
Small suggestion: display the buttons on hover for the main dmgs field?

**Comment by slcao2** [comment]
@DarKDinDoN yeah I went back and forth a little bit on whether to hide it and have it display on hover or not. I figured it would be obvious they were there if they just showed by default but I'll play around with the hover and see what works.

**Comment by slcao2** [comment]
@DarKDinDoN Went ahead with the hover to show. Give it a try!

**Comment by mech-tools** [comment]
@slcao2 Works like a charm!
Thx
