### ISSUE TITLE
Quick rolls for hit dice

### ISSUE THREAD

**Issue by pipefox** [slcao2/FoundryVTT-QuickRolls#39]
The hit dice button on short rests (in Foundry 0.7.9, D&D5e 1.2.0) can also benefit from quick rolling.

**Comment by slcao2** [comment]
@pipefox Feature should be implemented. Give it a try!

**Comment by pipefox** [comment]
Just tested it: hit dice rolling works flawlessly! Thanks a lot and Happy Holidays!

**Comment by slcao2** [comment]
Thanks! You too!
