### ISSUE TITLE
Roll sounds

### ISSUE THREAD

**Issue by mech-tools** [slcao2/FoundryVTT-QuickRolls#42]
Hello,

Quick roll could have a small dice sound to alert others players.
For public rolling at least.

**Comment by slcao2** [comment]
What sort of sound are you thinking of? I personally use Dice So Nice which has its own dice rolling sound which I would recommend if you're looking for something to alert your players. My main concern with this one would be if the dice alert sound would be too annoying or not mix well with other modules that also play sounds on rolls.

**Comment by mech-tools** [comment]
@slcao2 I kind of like the classic dice sound.
The Problem with Dice So Nice is the delay. You have to wait the dice to be visually rolled so the result is displayed.
And it slows things soooo much (even tho I like the animation)

**Comment by mech-tools** [comment]
Wait, didn't see the option to display chat cards immediately 😄
Probably added after I tested the Dice So Nice module.
That's great!

**Comment by slcao2** [comment]
@DarKDinDoN Was just about to comment about that option :) Is that fine for your needs?

**Comment by mech-tools** [comment]
Yep, that's great! Thx 😃

**Comment by slcao2** [comment]
Cool. Closing the issue then. As always, thanks for the suggestion.
