### ISSUE TITLE
Preview of the module on the GIT

### ISSUE THREAD

**Issue by DipsoNOR** [slcao2/FoundryVTT-QuickRolls#43]
With all the various modules having a bit of a preview/screenshot to let us see what your module looks like in action can be very useful. I already spend way to much time installing and testing modules to see if they fit my needs.

**Comment by slcao2** [comment]
@DipsoNOR If you check the wiki, there's a list of the features with some gifs and screenshots demoing the module. I previously had it on the readme in the homepage but moved it to conserve module sizing. Hope that helps!

**Comment by DipsoNOR** [comment]
> @DipsoNOR If you check the wiki, there's a list of the features with some gifs and screenshots demoing the module. I previously had it on the readme in the homepage but moved it to conserve module sizing. Hope that helps!

Yea i realized this, and that's why I closed the issue. :)
