### ISSUE TITLE
Chat message partially hidden

### ISSUE THREAD

**Issue by mech-tools** [slcao2/FoundryVTT-QuickRolls#45]
Hello,

I noticed that when a player is sending a chat message in the chat window, sometimes, the chat message is partially hidden. I need to scroll within the chat window to fully display the chat message
![image](https://user-images.githubusercontent.com/1687854/102983123-e7274780-450b-11eb-869c-d1b3c7374bc2.png)

**Comment by slcao2** [comment]
Hmm probably something to do with how the DOM replacements work. I could force the scrollbar to go to the bottom on chat rolls or something to fix it potentially but may be annoying if you're scrolling up in chat trying to search for something and someone rolls.

**Comment by mech-tools** [comment]
@slcao2 Forcing to scroll doesn't seem a good fix, I agree :/

**Comment by mech-tools** [comment]
@slcao2 Might not be perfect, but you could force scroll if the chat window is fully scrolled?
This way a user scrolling won't be bothered

Not sure that's the best way

**Comment by cs96and** [comment]
I think this happens regardless of whether Quick Rolls is enabled or not.

**Comment by slcao2** [comment]
@DarKDinDoN Hmm yeah can't really think of a better way than that so I'll go with that.
@cs96and I haven't seen it in the vanilla experience yet so I'm assuming it's related to something with the module. Given the fix shouldn't be too bad to implement, I'll give it a try and see how it feels.

**Comment by slcao2** [comment]
@cs96and Ah I see what you mean actually. In vanilla, it forces you down to the bottom whenever something gets rolled regardless of if you're scrolled up or not. I don't think I can override that behavior so I'll just force to the bottom for everything to match the vanilla experience.

**Comment by slcao2** [comment]
@DarKDinDoN Should be fixed. Give it a try!

**Comment by mech-tools** [comment]
@slcao2 Yep working 👍 
For the forcing of the scroll, it might be worth looking at this package: https://github.com/relick/FoundryVTT-Chat-Scrolling
The developer managed to not force the scrolling
