### ISSUE TITLE
Compatibility Issue with Skill Customization 5e

### ISSUE THREAD

**Issue by olavmueller** [slcao2/FoundryVTT-QuickRolls#51]
When I add a bonus into a skill for Skill Customization for 5e (+10 for example for a Stealth check under Pass without a trace) this bonus is not applied to the QR (1.5.1) roll. I don't know whether this is a QR or a SC problem.

**Comment by slcao2** [comment]
Looks like the issue here is the way we patch over the existing roll mechanics is similar and so they conflict with each other. Looking through the Skil Customization code, I may be able to patch around it to make it compatible. I'll give it a try and see what I can do.

**Comment by slcao2** [comment]
@olavmueller Should be fixed now. Give it a try!

**Comment by cs96and** [comment]
Excellent, I'd been meaning to raise a feature request for this too.  Thanks!

**Comment by olavmueller** [comment]
Great, thanks very much.
