### ISSUE TITLE
TypeError: item._getUsageUpdates is not a function

### ISSUE THREAD

**Issue by freedomischaos** [slcao2/FoundryVTT-QuickRolls#54]
> Uncaught (in promise) TypeError: item._getUsageUpdates is not a function
>     at Item5e.roll (itemOverrides.js:298)
>     at RollHandlerBase5e.rollItemMacro (dnd5e-base.js:98)
>     at RollHandlerBase5e._handleMacros (dnd5e-base.js:51)
>     at RollHandlerBase5e.doHandleActionEvent (dnd5e-base.js:27)
>     at RollHandlerBase5e.handleActionEvent (rollHandler.js:47)
>     at handleClick (tokenactionhud.js:86)
>     at HTMLDivElement.<anonymous> (tokenactionhud.js:93)
>     at HTMLDivElement.dispatch (jquery.min.js:2)
>     at HTMLDivElement.v.handle (jquery.min.js:2)

Having an interesting issue and hoping that you could help with it.

I do have a decently large list of modules on a foundryvtt 0.7.9 install, but when I disable Quick Rolls, the problem go away.

I am trying to use the Token Action HUD to make dice rolls that previously have worked but have stopped after some updates and observing the above error when attempting to make the rolls when attacking with a weapon or not. 

Other rolls function normally though it doesn't trigger 3D dice via Dice So Nice for anyone other than the character rolling where previously dice would appear on all user screens. It is still logged in chat though and Foundry appears to log the chat message was passed successfully. In player view or GM view, no errors appear in Chrome Dev Tools, the error above is only encountered on the person attempting to cast the dice.

Please let me know if you need anything else.

**Comment by slcao2** [comment]
@freedomischaos Hmm weird. I tried with Quick Rolls and the Token Action HUD enabled with the latest versions and I'm not seeing that error and the resource usage is being deducted correctly for a bow using arrows. My guess is that one of the modules you use is overriding the roll function on Item5e. Do you only see the error when rolling specific items? And it only happens rolling from the Token Action HUD? Can you provide a list of the modules you've enabled?

**Comment by freedomischaos** [comment]
Definitely could be another module was just hopeful it was this one as it goes away when disabled and the HUD works though still gotta use the chat buttons to roll dice. 

It is only with the Weapons (even using a Longsword) with Quick Rolls enabled that I'm encountering the error message. I can do skills/saves via the HUD queue successfully.

![image](https://user-images.githubusercontent.com/7773973/103182765-e67c1180-487b-11eb-8b86-7548d1f7ba82.png)

The unfortunate thing is that it was working a bit ago, just last week updated to 0.7.9 and everything worked still and did an update.

The help is much appreciated, thanks.

```
resourcesplus--v1.6.2;
about-face--v2.0.3;
all-goblins-have-names--v1.2.0;
alternative-rotation--v1.1.0;
foundryvtt-always-show-rolls--v1.0.0;
backgroundless-pins--v1.2.0;
baileywiki-maps--v0.2.1;
better-target--v0.1.9;
bubblerolls--v1.1.2;
buttonoverflow--v0.0.1;
chatdamagebuttons-beyond20--v1.1.2;
chat-portrait--v0.2.1;
chat-scrolling--v0.0.8;
combat-enhancements--v0.1.7;
foundry-combat-focus--v1.3.0;
combatready--v1.1.10;
5e-training--v0.4.9;
dndAudioBundle-HammerHome--v1.2;
ddb-importer--v0.2.13;
sceneDefaults--v1.0.0;
dice-so-nice--v3.2.1;
dice-tooltip--v1.0.8;
dice-calculator--v0.6.6;
dnd5e-helpers--v1.8.3;
dndbeyond-character-sheet--v1.6.1;
dndbeyond-npc-sheet--v1.0.2;
dww-battlemaps--v1.1.0;
dragupload--v1.5.3;
foundry-drmapzo-free--v0.18.0;
Dynamic-Effects-SRD--v4.0.31;
dae--v0.2.30;
easy-exports--v0.5.1;
fogmanager--v0.1.4;
forien-copy-environment--v1.1.1;
forien-unidentified-items--v0.2.5;
foundry_community_macros--v0.31;
workshop-welcome-screen--v1.0.7;
fudge--v1.1.0;
gAudioBundle-1--v2.3;
gAudioBundle-2--v2.4;
gAudioBundle-3--v2.3;
gAudioBundle-4--v2.4;
group-initiative--v1.4.0;
grouproll--v0.7.0;
healthEstimate--v2.4.0;
hidden-initiative--v0.3.2;
hide-gm-rolls--v0.6.3;
vtta-iconizer--v2.1.15;
illandril-npc-quick-actions--v1.0.1;
laptop-fix--v0.0.8;
lmrtfy--v1.5;
colorsettings--v2.5.7;
lib-wrapper--v1.0.5.3;
lootsheetnpc5e--v2.2.2;
free-loot-tavern-compendium--v1.6.1;
max-crit--v0.1.7;
mikwewa-cave--v1.0.0;
mikwewa-crypt--v1.0.0;
mikwewa-gauntlet--v1.0.0;
mikwewa-graveyard--v1.0.0;
mikwewa-temples--v1.0.0;
mikwewa-helmet-cave--v1.0.0;
mikwewa-igloo--v1.0.0;
mikwewa-estate--v1.0.0;
mikwewa-prison--v1.0.0;
mikwewa-ring--v1.0.0;
mikwewa-sewer-temple--v1.0.0;
mikwewa-church--v1.0.0;
mikwewa-fortress--v1.0.0;
mikwewa-tavern--v1.0.0;
miskasmaps--v1.2;
mikwewa-free--v1.3.0;
narrator-tools--v0.35;
noback--v0.0.2;
npcgen--v0.2.4;
NotYourTurn--v1.1.2;
tomcartos-ostenwold--v1.1.1;
fvtt-party-resources--v1.1.3;
perfect-vision--v1.2.19;
permission_viewer--v0.8;
personalmarkers--v1.0.6;
pick-up-stix--v0.13.8;
pings--v1.2.10;
quick-insert--v2.4.1;
quick-rolls--v1.5.2;
roll-from-compendium--v1.0.3;
ShowDragDistance--v2.2.3;
foundryvtt-show-notes--v0.3;
spellarena--v1.3.0;
spellTemplateManager--v0.4.1;
SupplementalBestiary--v2.2.0;
tabbed-chatlog--v1.5.7;
tacticalmap-free--v1.1.0;
mad-cartographer-free-maps--v1.0.1;
tidy-ui_game-settings--v0.1.21;
token-action-hud--v0.10.14;
token-factions--v0.2.1;
token-info-icons--v2.2.0;
vtta-tokenizer--v2.2.4;
torch--v1.1.4;
```

**Comment by freedomischaos** [comment]
I think I may have found my root issue. My game rule data was on dnd5e 1.1.1, I've updated to 1.2.0 and error goes away though may have a slightly different issue with dice not appearing though that might be a different module and I can do some more testing later this week.

**Comment by slcao2** [comment]
Ah cool yeah in dnd5e 1.2.0 they refactored some things around the rolling which is probably what was causing the error with the item._getUsageUpdates is not a function error.

**Comment by freedomischaos** [comment]
Yeah, was just reading over their notes. Thanks for looking into it anyway. Can close. I'll re-open/create new if I encounter something else. Thanks again for the assist.
