### ISSUE TITLE
Chat not scrolling

### ISSUE THREAD

**Issue by erkocze** [slcao2/FoundryVTT-QuickRolls#55]
When I roll an attack the chat doesn't seem to move enought and I have to scroll manually.

![obrazek](https://user-images.githubusercontent.com/30783824/103244461-69c16400-495d-11eb-890a-c15a316780e9.png)

Doesn't move when I roll for damage either (even if "auto roll damage" is on).

![obrazek](https://user-images.githubusercontent.com/30783824/103244545-a1c8a700-495d-11eb-9af4-66db52f78337.png)

**Comment by slcao2** [comment]
@erkocze Hmm are you using the latest version (1.5.2)? And can you provide the browser you are using? I am not seeing this issue happen on my end.

**Comment by erkocze** [comment]
I uninstalled several old modules and the issue is fixed now. Thanks for your time.

**Comment by slcao2** [comment]
Nice! Glad it's working for you. Closing the issue.
