### ISSUE TITLE
Token Action HUD integration

### ISSUE THREAD

**Issue by SpartyInDetroit** [slcao2/FoundryVTT-QuickRolls#58]
[Token Action HUD](https://github.com/espositos/fvtt-tokenactionhud) is a useful module that allows a player to perform common actions without opening character sheets. The developer provides a method for creating custom handlers for alternative roll systems (better rolls and minor-qol are currently supported for example). Have you given any thought to creating a custom handler for Quick Rolls? If not, I'd be willing to take a crack at it with your blessing (I'd also need to get in contact with the creator of Token Action HUD to get his blessing as well).

**Comment by slcao2** [comment]
@SpartyInDetroit I haven't given it any thought but I did try it out just now with Token Action HUD and Quick Rolls enabled and it seems like everything is working properly with the default handler that is there. Is there something you are seeing that is not working or is there something with the custom handler that you're looking to achieve?

**Comment by SpartyInDetroit** [comment]
Well that's embarrassing. I just tested it out and it actually does look like it's working. I was experimenting with different dice roll systems today and a few of them had issues, for some reason I thought your module was one of them, good to know it's not! Sorry for the confusion.

**Comment by slcao2** [comment]
Np glad it's working for you!
