### ISSUE TITLE
Display damage type associate with the damage rolls

### ISSUE THREAD

**Issue by slcao2** [slcao2/FoundryVTT-QuickRolls#6]
It can be hard to tell what damage type each die roll is. Probably would be nice to show the damage type of each part of the damage roll.

**Comment by mech-tools** [comment]
Hey great idea.
Also, similarly to BetterRolls, it would be great to have a description field as well. Cause some dmgs only apply to specific targets or under specific conditions

**Comment by slcao2** [comment]
@DarKDinDoN I believe the description should show properly currently unless I'm misunderstanding your intent here. The description should show above the roll buttons, with the chat flavor showing above the description and the activation condition showing in the footer or something like that. Was there something else you were looking for with this?

**Comment by mech-tools** [comment]
@slcao2 not quite.

Let me take an example from BetterRolls.

Here is a weapon configuration for a Paladin:
![image](https://user-images.githubusercontent.com/1687854/101467915-3fbee800-3943-11eb-899a-0cdf6a09d568.png)
For each type of dmgs there is an added description field.

When the item is in chat:
![image](https://user-images.githubusercontent.com/1687854/101468015-63822e00-3943-11eb-82a1-a46f54961fa1.png)
We can read the dmg type and description field for each type of dmgs

This is especially useful to know which type of dmgs is which and having the description field displayed there as well allows the party to know when and how it is applied.

In this example, both "Undead & fiends" and "Improved Divine Smite" are using the same roll formula. Without the description, players can't really know which is which.

**Comment by slcao2** [comment]
@DarKDinDoN Ah gotcha I see what you mean. I think that might be difficult to accommodate since it involves modifying the sheet itself. The scope of that seems a little outside of what I'm trying to accomplish with this module. I probably won't be able to add something like that anytime soon but I'll definitely keep that in mind when I'm thinking about more features to add. Thanks for the suggestion!
