### ISSUE TITLE
Reliable Talent bug

### ISSUE THREAD

**Issue by OtavioLhamas** [slcao2/FoundryVTT-QuickRolls#8]
When Reliable Talent is enabled, attacks rolls with proficiency are rolled using "{1d20,10}kh" formula, not only ability checks. Tested on a new world with only Quick Rolls v1.0.1 enabled, on Foundry 0.7.7, DnD 5e 1.1.1.
As you can see in the following screenshot, the first roll was made with Quick Rolls enabled, the second one disabled: https://prnt.sc/vsi364
I could not reproduce the issue with saving throws or tools.

**Comment by slcao2** [comment]
Ah good catch. Looks like I missed that part when taking pieces out of the dnd5e system. Should be an easy enough fix.

**Comment by slcao2** [comment]
@OtavioLhamas Fix should be out. Hope it's working properly for you.
